"""What this build is made of — versions and paths, as plain data.

Feeds the About dialog and is worth having separately from it: "what am I
actually running" is the first question of any support conversation, and a
function that answers it can be called from a test, a log line, or a bug
report without opening a window.

UI-free by the same rule the rest of ``core`` follows — no Qt, no English
sentences, just the facts and their labels.
"""

from __future__ import annotations

import platform
import subprocess
from dataclasses import dataclass

from loguru import logger

#: How long to wait for ``mpv --version``. A local exec answers in tens of
#: milliseconds; the timeout exists so a wedged or missing binary cannot hang
#: the dialog that is trying to describe it.
_MPV_VERSION_TIMEOUT_S = 2.0


@dataclass(frozen=True)
class ComponentVersions:
    """Versions and locations of the things this build runs on.

    Attributes:
        app: MetaTV's own version string.
        build_id: The packaged build identifier (``<version>+<date>.<sha>``),
            or ``None`` in a source checkout where it is not generated.
        python: Python version.
        qt: Qt runtime version.
        pyqt: PyQt binding version.
        platform_name: OS and release.
        mpv: mpv's version string, or ``None`` when it could not be asked.
        mpv_path: Where the mpv binary was resolved from — the vendored copy
            inside the app bundle, or one found on PATH. Worth showing: "which
            mpv is it actually using" has been a real support question.
    """

    app: str
    build_id: str | None
    python: str
    qt: str
    pyqt: str
    platform_name: str
    mpv: str | None
    mpv_path: str | None


def _mpv_version(binary: str) -> str | None:
    """First line of ``mpv --version``, trimmed to the version itself.

    Returns ``None`` rather than raising: a missing or broken mpv is a thing
    the dialog should REPORT, not a reason for it to fail to open.
    """
    try:
        out = subprocess.run(
            [binary, "--version"],
            capture_output=True, text=True, timeout=_MPV_VERSION_TIMEOUT_S,
        )
    except (OSError, subprocess.SubprocessError) as exc:
        logger.debug(f"could not read mpv version from {binary!r}: {exc}")
        return None

    first = (out.stdout or "").splitlines()
    if not first:
        return None
    # "mpv 0.38.0 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects"
    parts = first[0].split()
    return parts[1] if len(parts) > 1 and parts[0] == "mpv" else first[0].strip()


def collect() -> ComponentVersions:
    """Gather everything the About dialog reports."""
    from PyQt6.QtCore import PYQT_VERSION_STR, QT_VERSION_STR

    from metatv import __version__

    try:
        from metatv._build_id import BUILD_ID
    except ImportError:
        # _build_id.py is generated by the packaging step and gitignored, so
        # its absence is the NORMAL state of a source checkout, not a failure —
        # which is why this reports "source checkout" rather than staying quiet.
        #
        # Narrow on purpose: `except Exception` here would also swallow a
        # genuinely broken generated file (a syntax error, a bad write) and
        # render it as an ordinary checkout, hiding a packaging bug in the one
        # dialog built to identify the build.
        BUILD_ID = None

    mpv_path: str | None
    try:
        from metatv.core.players.mpv import _resolve_mpv_binary

        mpv_path = _resolve_mpv_binary()
    except Exception as exc:                       # pragma: no cover - defensive
        logger.debug(f"could not resolve the mpv binary: {exc}")
        mpv_path = None

    return ComponentVersions(
        app=__version__,
        build_id=BUILD_ID,
        python=platform.python_version(),
        qt=QT_VERSION_STR,
        pyqt=PYQT_VERSION_STR,
        platform_name=f"{platform.system()} {platform.release()}",
        mpv=_mpv_version(mpv_path) if mpv_path else None,
        mpv_path=mpv_path,
    )
