"""Gruvbox scales, in the same 12-step shape the Radix ones use.

GENERATED by scripts/build_gruvbox_scales.py — regenerate rather than hand-edit.

Gruvbox is a published palette, not a generated scale system: it defines a
neutral ramp (bg0_h -> fg1) and exactly TWO steps per accent, normal and bright.
This module maps those onto Radix's twelve steps so the existing token layer
resolves a Gruvbox palette exactly like any other — every role name, legacy_map
entry and OVERLAY_* alpha keeps working untouched.

Published values are used verbatim wherever they land:

* NEUTRAL is twelve real Gruvbox values. No interpolation at all.
* Accent step 9 is the published *normal* and step 10 the published *bright* —
  precisely the two Radix steps that mean solid fill and solid hover, which is
  what those two Gruvbox values are for.

Steps 1-8 and 11-12 are derived, because Gruvbox does not publish them. Three
things shape the derivation and every one was set by a failing test:

* 11-12 LIGHTEN the bright step in HLS with a saturation floor, rather than
  interpolating toward the cream foreground. Lerping washed the hue out —
  yellow.11 and orange.11 landed on the same pale sand and the quality chips
  stopped being tellable apart.
* Lightening is CAPPED below the title's own luminance. Gruvbox's olive green
  lightens into a yellow-green so luminous it out-shouted the row title
  (12.32:1 against the title's 11.95:1), inverting the row hierarchy.
* ...but the target is high enough that a low-luminance hue still clears AA on
  the SELECTION tint, where purple sat at 3.35:1 when the target was lower.
  The two constraints pull opposite ways, which is why they are stated as
  numbers in the generator rather than tuned by eye.

Its own module because radix.py is vendored and says DO NOT hand-edit.
"""
from __future__ import annotations

GRUVNEUTRAL_DARK: tuple[str, ...] = (
    "#0d0e0f", "#1d2021", "#242424", "#282828",
    "#32302f", "#3c3836", "#504945", "#665c54",
    "#7c6f64", "#928374", "#bdae93", "#ebdbb2",
)

GRUVNEUTRAL_A_DARK: tuple[str, ...] = (
    "#ebdbb200", "#ebdbb209", "#ebdbb214", "#ebdbb21d",
    "#ebdbb225", "#ebdbb230", "#ebdbb240", "#ebdbb25d",
    "#ebdbb26d", "#ebdbb27b", "#ebdbb2b5", "#ebdbb2ef",
)

GRUVRED_DARK: tuple[str, ...] = (
    "#2a0706", "#340907", "#4a0d0b", "#5c100d",
    "#6c130f", "#841713", "#a71e18", "#d2251e",
    "#cc241d", "#fb4934", "#fc6250", "#fd8e82",
)

GRUVRED_A_DARK: tuple[str, ...] = (
    "#fb493400", "#fb493409", "#fb493414", "#fb49341d",
    "#fb493425", "#fb493430", "#fb493440", "#fb49345d",
    "#fb49346d", "#fb49347b", "#fb4934b5", "#fb4934ef",
)

GRUVGREEN_DARK: tuple[str, ...] = (
    "#151404", "#1a1904", "#262606", "#303008",
    "#39380a", "#46450c", "#59590f", "#706f13",
    "#98971a", "#b8bb26", "#b8bb26", "#b8bb26",
)

GRUVGREEN_A_DARK: tuple[str, ...] = (
    "#b8bb2600", "#b8bb2609", "#b8bb2614", "#b8bb261d",
    "#b8bb2625", "#b8bb2630", "#b8bb2640", "#b8bb265d",
    "#b8bb266d", "#b8bb267b", "#b8bb26b5", "#b8bb26ef",
)

GRUVYELLOW_DARK: tuple[str, ...] = (
    "#1a1304", "#211705", "#2f2207", "#3c2a09",
    "#47330b", "#583f0d", "#705011", "#8d6516",
    "#d79921", "#fabd2f", "#fabd2f", "#fabd2f",
)

GRUVYELLOW_A_DARK: tuple[str, ...] = (
    "#fabd2f00", "#fabd2f09", "#fabd2f14", "#fabd2f1d",
    "#fabd2f25", "#fabd2f30", "#fabd2f40", "#fabd2f5d",
    "#fabd2f6d", "#fabd2f7b", "#fabd2fb5", "#fabd2fef",
)

GRUVBLUE_DARK: tuple[str, ...] = (
    "#081616", "#0b1b1c", "#0f2729", "#143334",
    "#173c3d", "#1d4a4c", "#245d60", "#2e767a",
    "#458588", "#83a598", "#83a598", "#58bf98",
)

GRUVBLUE_A_DARK: tuple[str, ...] = (
    "#83a59800", "#83a59809", "#83a59814", "#83a5981d",
    "#83a59825", "#83a59830", "#83a59840", "#83a5985d",
    "#83a5986d", "#83a5987b", "#83a598b5", "#83a598ef",
)

GRUVPURPLE_DARK: tuple[str, ...] = (
    "#220d16", "#2b101c", "#3d1729", "#4c1d33",
    "#5b233c", "#702b4a", "#8e365e", "#b44477",
    "#b16286", "#d3869b", "#d3869b", "#db9cae",
)

GRUVPURPLE_A_DARK: tuple[str, ...] = (
    "#d3869b00", "#d3869b09", "#d3869b14", "#d3869b1d",
    "#d3869b25", "#d3869b30", "#d3869b40", "#d3869b5d",
    "#d3869b6d", "#d3869b7b", "#d3869bb5", "#d3869bef",
)

GRUVAQUA_DARK: tuple[str, ...] = (
    "#091709", "#0b1d0b", "#102911", "#143415",
    "#183e19", "#1d4c1f", "#256127", "#2f7b32",
    "#689d6a", "#8ec07c", "#8ec07c", "#8ec07c",
)

GRUVAQUA_A_DARK: tuple[str, ...] = (
    "#8ec07c00", "#8ec07c09", "#8ec07c14", "#8ec07c1d",
    "#8ec07c25", "#8ec07c30", "#8ec07c40", "#8ec07c5d",
    "#8ec07c6d", "#8ec07c7b", "#8ec07cb5", "#8ec07cef",
)

GRUVORANGE_DARK: tuple[str, ...] = (
    "#220f02", "#2a1203", "#3d1a04", "#4d2105",
    "#5b2706", "#703007", "#8e3d09", "#b34e0c",
    "#d65d0e", "#fe8019", "#fe8019", "#fe933b",
)

GRUVORANGE_A_DARK: tuple[str, ...] = (
    "#fe801900", "#fe801909", "#fe801914", "#fe80191d",
    "#fe801925", "#fe801930", "#fe801940", "#fe80195d",
    "#fe80196d", "#fe80197b", "#fe8019b5", "#fe8019ef",
)

GRUVNEUTRAL_LIGHT: tuple[str, ...] = (
    "#f9f5d7", "#fbf1c7", "#f2e5bc", "#ebdbb2",
    "#d5c4a1", "#bdae93", "#a89984", "#928374",
    "#7c6f64", "#665c54", "#504945", "#3c3836",
)

GRUVNEUTRAL_A_LIGHT: tuple[str, ...] = (
    "#3c383600", "#3c383609", "#3c383614", "#3c38361d",
    "#3c383625", "#3c383630", "#3c383640", "#3c38365d",
    "#3c38366d", "#3c38367b", "#3c3836b5", "#3c3836ef",
)

GRUVRED_LIGHT: tuple[str, ...] = (
    "#faebc2", "#f8e3bb", "#f5d8b3", "#f3cca8",
    "#efbc9b", "#e89f83", "#e07a64", "#d65142",
    "#cc241d", "#9d0006", "#9d0006", "#9d0006",
)

GRUVRED_A_LIGHT: tuple[str, ...] = (
    "#9d000600", "#9d000609", "#9d000614", "#9d00061d",
    "#9d000625", "#9d000630", "#9d000640", "#9d00065d",
    "#9d00066d", "#9d00067b", "#9d0006b5", "#9d0006ef",
)

GRUVGREEN_LIGHT: tuple[str, ...] = (
    "#f8eec2", "#f4ebbb", "#efe6b2", "#e9e1a8",
    "#e1da9a", "#d3cd82", "#c2bd63", "#aeab40",
    "#98971a", "#79740e", "#736f0d", "#58550a",
)

GRUVGREEN_A_LIGHT: tuple[str, ...] = (
    "#79740e00", "#79740e09", "#79740e14", "#79740e1d",
    "#79740e25", "#79740e30", "#79740e40", "#79740e5d",
    "#79740e6d", "#79740e7b", "#79740eb5", "#79740eef",
)

GRUVYELLOW_LIGHT: tuple[str, ...] = (
    "#faeec2", "#f8ebbb", "#f7e6b3", "#f5e1a9",
    "#f2da9c", "#edce85", "#e6be67", "#dfac46",
    "#d79921", "#b57614", "#966111", "#714a0d",
)

GRUVYELLOW_A_LIGHT: tuple[str, ...] = (
    "#b5761400", "#b5761409", "#b5761414", "#b576141d",
    "#b5761425", "#b5761430", "#b5761440", "#b576145d",
    "#b576146d", "#b576147b", "#b57614b5", "#b57614ef",
)

GRUVBLUE_LIGHT: tuple[str, ...] = (
    "#f6eec5", "#eee9c3", "#e5e4bf", "#dadebc",
    "#ccd5b7", "#b2c6ae", "#91b2a2", "#6d9d96",
    "#458588", "#076678", "#076678", "#065a6a",
)

GRUVBLUE_A_LIGHT: tuple[str, ...] = (
    "#07667800", "#07667809", "#07667814", "#0766781d",
    "#07667825", "#07667830", "#07667840", "#0766785d",
    "#0766786d", "#0766787b", "#076678b5", "#076678ef",
)

GRUVPURPLE_LIGHT: tuple[str, ...] = (
    "#f9edc5", "#f6e7c2", "#f2e0bf", "#eed7bb",
    "#e8ccb6", "#ddb8ad", "#d09ea1", "#c18194",
    "#b16286", "#8f3f71", "#8f3f71", "#873367",
)

GRUVPURPLE_A_LIGHT: tuple[str, ...] = (
    "#8f3f7100", "#8f3f7109", "#8f3f7114", "#8f3f711d",
    "#8f3f7125", "#8f3f7130", "#8f3f7140", "#8f3f715d",
    "#8f3f716d", "#8f3f717b", "#8f3f71b5", "#8f3f71ef",
)

GRUVAQUA_LIGHT: tuple[str, ...] = (
    "#f7eec4", "#f1ebc0", "#e9e7bc", "#e1e2b6",
    "#d5dbaf", "#c0cfa2", "#a6c091", "#88af7e",
    "#689d6a", "#427b58", "#2e7a4b", "#235d3a",
)

GRUVAQUA_A_LIGHT: tuple[str, ...] = (
    "#427b5800", "#427b5809", "#427b5814", "#427b581d",
    "#427b5825", "#427b5830", "#427b5840", "#427b585d",
    "#427b586d", "#427b587b", "#427b58b5", "#427b58ef",
)

GRUVORANGE_LIGHT: tuple[str, ...] = (
    "#faedc1", "#f8e7ba", "#f7dfb1", "#f4d6a6",
    "#f1cb97", "#ecb67d", "#e69b5c", "#de7e37",
    "#d65d0e", "#af3a03", "#af3a03", "#943103",
)

GRUVORANGE_A_LIGHT: tuple[str, ...] = (
    "#af3a0300", "#af3a0309", "#af3a0314", "#af3a031d",
    "#af3a0325", "#af3a0330", "#af3a0340", "#af3a035d",
    "#af3a036d", "#af3a037b", "#af3a03b5", "#af3a03ef",
)

