#!/usr/bin/env python3
"""Regenerate metatv/gui/tokens/gruvbox.py from the published Gruvbox values.

Run:  venv/bin/python scripts/build_gruvbox_scales.py > metatv/gui/tokens/gruvbox.py

Kept as a script for the same reason scripts/build_font_assets.py is: the output
is derived, and a derived file nobody can regenerate is a file nobody can safely
change. The two tunables (STEP_11_L / STEP_12_L) are why — both were set by a
failing test, not by eye, and the next person to move them needs to be able to
re-run the gates against the result.
"""
from __future__ import annotations

import colorsys

# ── The published Gruvbox values ────────────────────────────────────────────
NEUTRAL = ["#1d2021", "#282828", "#32302f", "#3c3836", "#504945", "#665c54",
           "#7c6f64", "#928374", "#a89984", "#bdae93", "#d5c4a1", "#ebdbb2"]
ACCENTS = {
    "GRUVRED":    ("#cc241d", "#fb4934"),
    "GRUVGREEN":  ("#98971a", "#b8bb26"),
    "GRUVYELLOW": ("#d79921", "#fabd2f"),
    "GRUVBLUE":   ("#458588", "#83a598"),
    "GRUVPURPLE": ("#b16286", "#d3869b"),
    "GRUVAQUA":   ("#689d6a", "#8ec07c"),
    "GRUVORANGE": ("#d65d0e", "#fe8019"),
}
BG = "#282828"
FG1 = "#ebdbb2"

# ── Tunables, both set by a failing test ────────────────────────────────────
# High enough that a low-luminance hue still clears 4.5:1 on the SELECTION
# tint. Purple is the binding case: COLOR_ROW_PLATFORM measured 3.35:1 at 0.66
# and 4.43:1 at 0.74 — both under the floor — and clears at 0.78. This is the
# LOWEST value that passes every gate, which keeps the most headroom under the
# title's luminance ceiling below.
STEP_11_L, STEP_12_L = 0.78, 0.86
# ...and capped below the title's own luminance, because Gruvbox's olive green
# lightens into a yellow-green that out-shouted the row title at 12.32:1.
CEILING_FRACTION = 0.92
SAT_FLOOR = 0.45


def _hx(c):
    return tuple(int(c.lstrip("#")[i:i + 2], 16) for i in (0, 2, 4))


def _st(r, g, b):
    return f"#{r:02x}{g:02x}{b:02x}"


def _lerp(a, b, t):
    A, B = _hx(a), _hx(b)
    return _st(*(round(A[i] + (B[i] - A[i]) * t) for i in range(3)))


def _lum(c):
    def ch(v):
        v /= 255
        return v / 12.92 if v <= 0.03928 else ((v + 0.055) / 1.055) ** 2.4
    r, g, b = _hx(c)
    return 0.2126 * ch(r) + 0.7152 * ch(g) + 0.0722 * ch(b)


CEIL = _lum(FG1) * CEILING_FRACTION


def _lighten(c, target_l):
    r, g, b = (v / 255 for v in _hx(c))
    h, _l, s = colorsys.rgb_to_hls(r, g, b)
    s = max(s, SAT_FLOOR)
    out = c
    while target_l > 0.05:
        rr, gg, bb = colorsys.hls_to_rgb(h, target_l, s)
        out = _st(round(rr * 255), round(gg * 255), round(bb * 255))
        if _lum(out) <= CEIL:
            break
        target_l -= 0.02
    return out


def accent_scale(normal, bright):
    lo = [_lerp(BG, normal, t) for t in (0.06, 0.14, 0.24, 0.34, 0.45, 0.58, 0.72, 0.86)]
    return lo + [normal, bright, _lighten(bright, STEP_11_L), _lighten(bright, STEP_12_L)]


def alpha_scale(solid):
    r, g, b = _hx(solid)
    return [f"#{r:02x}{g:02x}{b:02x}{a:02x}" for a in
            (0x00, 0x09, 0x14, 0x1d, 0x25, 0x30, 0x40, 0x5d, 0x6d, 0x7b, 0xb5, 0xef)]


def _emit(name, vals):
    print(f"{name}: tuple[str, ...] = (")
    for i in range(0, 12, 4):
        print("    " + ", ".join(f'"{v}"' for v in vals[i:i + 4]) + ",")
    print(")\n")


def main():
    print(DOC)
    print("from __future__ import annotations")
    print()
    _emit("GRUVNEUTRAL_DARK", NEUTRAL)
    _emit("GRUVNEUTRAL_A_DARK", alpha_scale(FG1))
    for name, (normal, bright) in ACCENTS.items():
        _emit(f"{name}_DARK", accent_scale(normal, bright))
        _emit(f"{name}_A_DARK", alpha_scale(bright))


DOC = '''"""Gruvbox scales, in the same 12-step shape the Radix ones use.

GENERATED by scripts/build_gruvbox_scales.py — regenerate rather than hand-edit.

Gruvbox is a published palette, not a generated scale system: it defines a
neutral ramp (bg0_h -> fg1) and exactly TWO steps per accent, normal and bright.
This module maps those onto Radix's twelve steps so the existing token layer
resolves a Gruvbox palette exactly like any other — every role name, legacy_map
entry and OVERLAY_* alpha keeps working untouched.

Published values are used verbatim wherever they land:

* NEUTRAL is twelve real Gruvbox values. No interpolation at all.
* Accent step 9 is the published *normal* and step 10 the published *bright* —
  precisely the two Radix steps that mean solid fill and solid hover, which is
  what those two Gruvbox values are for.

Steps 1-8 and 11-12 are derived, because Gruvbox does not publish them. Three
things shape the derivation and every one was set by a failing test:

* 11-12 LIGHTEN the bright step in HLS with a saturation floor, rather than
  interpolating toward the cream foreground. Lerping washed the hue out —
  yellow.11 and orange.11 landed on the same pale sand and the quality chips
  stopped being tellable apart.
* Lightening is CAPPED below the title's own luminance. Gruvbox's olive green
  lightens into a yellow-green so luminous it out-shouted the row title
  (12.32:1 against the title's 11.95:1), inverting the row hierarchy.
* ...but the target is high enough that a low-luminance hue still clears AA on
  the SELECTION tint, where purple sat at 3.35:1 when the target was lower.
  The two constraints pull opposite ways, which is why they are stated as
  numbers in the generator rather than tuned by eye.

Its own module because radix.py is vendored and says DO NOT hand-edit.
"""'''


if __name__ == "__main__":
    main()
